### ISSUE TITLE
Building problems

### ISSUE THREAD

**Issue by Enrique-SC** [sdwfrost/gbmunge#4]
Hello, I'm excited about using your program. However, I'm having problems with the building part:

git clone https://github.com/sdwfrost/gbmunge
cd gbmunge (Evertything fine until this point)
make (When I run this, the executable gbmunge is not created in src. Instead, I get things like: make -C src, make[1]: Nothing to be done for 'release' )

Thank you for your help.

**Comment by sdwfrost** [comment]
Apologies for the late reply - I don't get this when I try. Try running:

```
cd gbmunge
make clean
make
```

There isn't a binary in the repository, so the default instructions should work.
